### ISSUE TITLE
Mock EDV APIs

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/edv#11]
Mock EDV APIs for storage to allow plugging Implementation later on.

- [x] Basic API implementation, simple in-memory store trustbloc/edge-store#27
- [x] Implement EDV client trustbloc/edv#3
- [x] EDV Docker image #14 
- [x] Client BDD test

(No encryption or authentication, using StructuredDocuments instead of EncryptedDocuments for now)
