### ISSUE TITLE
Improvements to support TrustBloc wallet functionality

### ISSUE THREAD

**Issue by DRK3** [trustbloc/edv#230]
Improvements to be made to support [wallet](https://github.com/trustbloc/wallet).

### Features

- [ ] Support multiple key-value attribute pairs for the `query` endpoint (#118)
- [ ] Pagination support (#168). Note: the spec is missing pagination syntax - it will need to be added (https://github.com/decentralized-identity/edv-spec/issues/14)

### Performance Optimization

- [ ] When using MongoDB, we can reduce number of calls to the database and the number of documents created by eliminating the need for "mapping documents". This will require a redesign... it may require a custom storage implementation rather than using the one in aries-framework-go (#218)
